# Generated by Django 5.0.4 on 2024-04-26 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_alter_itemestoque_cor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemestoque',
            old_name='tamano',
            new_name='tamanho',
        ),
    ]
